spring:
  profiles:
    active:
    - dev
  application:
    name: product-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
server:
  port: 8083
springdoc:
  api-docs:
    path: /api-docs
